### PR TITLE
Add parameter to enable/disable requiring the enable button to be held for motion

### PR DESCRIPTION
**Pull request by ghost**
Currently for the teleop_twist_joy node to output the Twist message an enable button needs to be active in the Joy message. This change adds a parameter called require_enable_button to toggle requiring the enable button to be active for motion. #20

### CODE REVIEW

**Comment by ghost** [comment]
@clalancette

**Review by clalancette — CHANGES_REQUESTED** [review]
The changes themselves look good to me.  Could you also add a new test in the `test` directory for this functionality?

**Comment by clalancette** [comment]
I made sure that the new test is called in ebfa11d.  With that, I'm happy with this, so I'll approve and merge.  Thanks for the contribution!

**Review by clalancette — APPROVED** [review]

**Comment by ghost** [comment]
Thank you Chris!

**Pull request merged**
